### ISSUE TITLE
Blurry text when using Nice Select

### ISSUE THREAD

**Issue by szymonryczek** [hernansartorio/jquery-nice-select#56]
I have a problem, when using Nice Select, during animation, all texts on the page are getting blurred. I noticed that on the jQuery Nice Select demo page there's no that issue. Ho to overcome this?

**Comment by jucacrispim** [comment]
Well, I know this is quite old, but I got the same issue and my solution was to change transition to none on .nice-select:afer.
```css
.nice-select:after{
  -webkit-transition: none;
  transition: none;
}
```
